// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMS.Infrastructure.Data;

#nullable disable

namespace VMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VMS.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "A stunning villa with a private beach view.",
                            ImageUrl = "https://villascroatia.com/storage/2020/08/modern-luxury-villa-pool-medulin-croatia-13-1.jpg",
                            Name = "Beachfront Villa",
                            Occupancy = 6,
                            Price = 1200.0,
                            Sqft = 2500
                        },
                        new
                        {
                            ID = 2,
                            Description = "A modern villa located on a scenic hillside.",
                            ImageUrl = "https://www.exceptionalvillas.com/public/upload/carousel/USA-Isola-Reunion-Resort-Orlando.jpg",
                            Name = "Luxury Hillside Villa",
                            Occupancy = 8,
                            Price = 1500.0,
                            Sqft = 3000
                        },
                        new
                        {
                            ID = 3,
                            Description = "A peaceful villa surrounded by lush greenery.",
                            ImageUrl = "https://img.jamesedition.com/listing_images/2019/11/22/15/56/26/81626a90-7b02-4a2c-b2f4-4fa897f54395/je/2000xxs.jpg",
                            Name = "Tropical Garden Villa",
                            Occupancy = 5,
                            Price = 1000.0,
                            Sqft = 2200
                        },
                        new
                        {
                            ID = 4,
                            Description = "A secluded villa with a private pool.",
                            ImageUrl = "https://imperiobanus.com/wp/wp-content/uploads/2018/04/1-1.jpg",
                            Name = "Private Pool Villa",
                            Occupancy = 10,
                            Price = 1800.0,
                            Sqft = 3500
                        },
                        new
                        {
                            ID = 5,
                            Description = "A cozy villa with breathtaking mountain views.",
                            ImageUrl = "https://wallpapercave.com/wp/wp10292952.jpg",
                            Name = "Mountain Retreat Villa",
                            Occupancy = 7,
                            Price = 1300.0,
                            Sqft = 2800
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
